language: csharp
solution: Dungeoneering.sln
deploy:
  provider: azure_web_apps
  on:
    branch: master
  skip_cleanup: true
#install:
#  - nuget restore solution-name.sln
#  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
#script:
#  - xbuild /p:Configuration=Release solution-name.sln
#  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyPoject.Tests/bin/Release/MyProject.Tests.dll